// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adtcsqqnhzmcybpxqhak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkdGNzcXFuaHptY3licHhxaGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NzEyMTUsImV4cCI6MjA5MDM0NzIxNX0.CJPThX1SobSA8wwig2zMOE7afYgxZ--HsiBBu_MQwSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
